In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\VIKASH KAUSHIK\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [4]:
lst = [[1,2,3], [1,2,3],[1,2,3]]

In [5]:
type(lst)

list

In [6]:
arr = np.array(lst)

In [7]:
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [10]:
board = [[1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,],
        [1,1,1,1,1,1,1,]]     

In [11]:
arr = np.array(board)

In [12]:
board = np.ones((8,8), dtype = int)
boolen = np.zeros((8,8), dtype = bool)

In [13]:
board

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [14]:
board = board * 13

In [15]:
np.array(board, dtype = bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [16]:
np.random.random((5,5))

array([[0.58623307, 0.35905499, 0.39709486, 0.49852241, 0.9414271 ],
       [0.97465182, 0.44245793, 0.8005245 , 0.28259453, 0.95658731],
       [0.90541052, 0.03236088, 0.70900515, 0.99023266, 0.65374713],
       [0.84250417, 0.197005  , 0.61140034, 0.85061046, 0.99705263],
       [0.94852952, 0.39670508, 0.1501404 , 0.66555301, 0.2802208 ]])

In [17]:
np.random.randint(0, 5, (5,5))

array([[1, 0, 1, 1, 2],
       [3, 1, 3, 3, 3],
       [2, 0, 3, 4, 2],
       [1, 2, 2, 1, 0],
       [2, 1, 0, 4, 4]])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])